name: Container Image Security Scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  trivy-scan:
    name: Trivy Vulnerability Scan
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Build Local Docker Image
      run: docker build -f app/Dockerfile -t local-fastapi:${{ github.sha }} ./app

    - name: Run Trivy Scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'local-fastapi:${{ github.sha }}'
        format: 'table'
        severity: 'HIGH,CRITICAL'
        exit-code: '1'